// ============================================================
//
//  Fields:
//    title             — book title (string)
//    genre             — see genre list at the bottom of this file
//    rating            — your star rating: 1–5  (5 = all-time favorite)
//    pages             — page count (drives trail length / particle speed)
//    emotionalIntensity — 1–5 (5 = most emotionally impactful for you)
//    year              — the year YOU READ it (not publication year)
//    finished          — omit (or true) for finished books;
//                        set to false for DNF → renders as a dashed trail
//
// ============================================================

const MY_BOOKS = [
  {
    title: "Rites of the Starling",
    genre: "Fantasy Romance",
    rating: 5,
    pages: 575,
    emotionalIntensity: 5,
    yOverride: 0.4,
    year: 2026,
  },
  {
    title: "Shield of Sparrows",
    genre: "Fantasy Romance",
    rating: 5,
    pages: 658,
    emotionalIntensity: 4,
    year: 2026,
  },
  {
    title: "Her Males",
    genre: "Sci-Fi Romance",
    rating: 3,
    pages: 396,
    emotionalIntensity: 2,
    year: 2025,
  },
  {
    title: "The Female",
    genre: "Sci-Fi Romance",
    rating: 3,
    pages: 397,
    emotionalIntensity: 2,
    year: 2025,
  },
  {
    title: "Apprentice to the Villain",
    genre: "Fantasy",
    rating: 2,
    pages: 368,
    emotionalIntensity: 1,
    year: 2023,
    finished: false,
  },
  {
    title: "Dry",
    genre: "Sci-Fo Dystopian",
    rating: 4,
    pages: 390,
    emotionalIntensity: 1,
    year: 2022,
    finished: false,
  },
  {
    title: "Manacled",
    genre: "Dark Fantasy",
    rating: 5,
    pages: 925,
    emotionalIntensity: 5,
    year: 2025,
  },
  {
    title: "A Twist of Luck",
    genre: "Paranormal Romance",
    rating: 4,
    pages: 424,
    emotionalIntensity: 1,
    year: 2025,
  },
  {
    title: "A Curse of Fate",
    genre: "Paranormal Romance",
    rating: 5,
    pages: 330,
    emotionalIntensity: 1,
    year: 2025,
  },
  {
    title: "The Ritual",
    genre: "Dark Romance",
    rating: 4,
    pages: 552,
    emotionalIntensity: 5,
    year: 2024,
  },
  {
    title: "Iron Flame",
    genre: "Fantasy Romance",
    rating: 4,
    pages: 623,
    emotionalIntensity: 1,
    year: 2024,
  },
  {
    title: "The Serpent and the Wings of Night",
    genre: "Fantasy Romance",
    rating: 4,
    pages: 504,
    emotionalIntensity: 4,
    year: 2023,
  },
  {
    title: "Fourth Wing",
    genre: "Fantasy Romance",
    rating: 5,
    pages: 665,
    emotionalIntensity: 5,
    year: 2023,
  },
  {
    title: "Savage Bonds",
    genre: "Fantasy Romance",
    rating: 4,
    pages: 500,
    emotionalIntensity: 5,
    year: 2023,
  },
  {
    title: "Broken Bonds",
    genre: "Fantasy Romance",
    rating: 4,
    pages: 289,
    emotionalIntensity: 5,
    year: 2023,
  },
  {
    title: "Savage Games",
    genre: "Dark Romance",
    rating: 2,
    pages: 324,
    emotionalIntensity: 1,
    year: 2022,
  },
  {
    title: "Queen of Shadows",
    genre: "Epic Fantasy",
    rating: 4,
    pages: 648,
    emotionalIntensity: 5,
    year: 2022,
  },
  {
    title: "Crown of Midnight",
    genre: "Epic Fantasy",
    rating: 4,
    pages: 420,
    emotionalIntensity: 4,
    year: 2022,
  },
  {
    title: "What Lies Beyond the Veil",
    genre: "Fantasy Romance",
    rating: 3,
    pages: 439,
    emotionalIntensity: 4,
    year: 2022,
  },
  {
    title: "Throne of Glass",
    genre: "Epic Fantasy",
    rating: 3,
    pages: 406,
    emotionalIntensity: 4,
    year: 2022,
  },
  {
    title: "Once Upon a Broken Heart",
    genre: "Fantasy Romance",
    rating: 3,
    pages: 408,
    emotionalIntensity: 3,
    year: 2021,
  },
  {
    title: "The Love Hypothesis",
    genre: "Contemporary Romance",
    rating: 5,
    pages: 383,
    emotionalIntensity: 5,
    xOverride: 0.3,
    yOverride: 0.35,
    year: 2021,
  },
  {
    title: "House of Sky and Breath",
    genre: "Urban Fantasy",
    rating: 4,
    pages: 805,
    emotionalIntensity: 5,
    year: 2022,
  },
  {
    title: "These Hollow Vows",
    genre: "Fantasy Romance",
    rating: 4,
    pages: 448,
    emotionalIntensity: 5,
    year: 2021,
  },
  {
    title: "The Traitor Queen",
    genre: "Fantasy Romance",
    rating: 4,
    pages: 352,
    emotionalIntensity: 5,
    year: 2021,
  },
  {
    title: "Gleam",
    genre: "Fantasy Romance",
    rating: 5,
    pages: 681,
    emotionalIntensity: 5,
    yOverride: 0.33,
    xOverride: 0.32,
    year: 2021,
  },
  {
    title: "Glint",
    genre: "Fantasy Romance",
    rating: 4,
    pages: 482,
    emotionalIntensity: 5,
    year: 2021,
  },
  {
    title: "Glow",
    genre: "Fantasy Romance",
    rating: 4,
    pages: 738,
    emotionalIntensity: 3,
    year: 2022,
  },
  {
    title: "Gild",
    genre: "Fantasy Romance",
    rating: 4,
    pages: 402,
    emotionalIntensity: 5,
    year: 2021,
  },
  {
    title: "Hollow Heathens",
    genre: "Fantasy",
    rating: 3,
    pages: 475,
    emotionalIntensity: 2,
    year: 2021,
    finished: false
  },
  {
    title: "A Deadly Education",
    genre: "Dark Academia",
    rating: 4,
    pages: 320,
    emotionalIntensity: 2,
    year: 2020,
  },
  {
    title: "Six of Crows",
    genre: "Fantasy",
    rating: 1,
    pages: 480,
    emotionalIntensity: 1,
    yOverride: 0.6,
    xOverride: 0.3,
    year: 2021,
    finished: false,
  },
  {
    title: "Corrupt",
    genre: "Dark Romance",
    rating: 0,
    pages: 461,
    emotionalIntensity: 1,
    year: 2021,
  },
  {
    title: "Emergency Skin",
    genre: "Sci-Fi",
    rating: 3,
    pages: 38,
    emotionalIntensity: 3,
    year: 2021,
  },
  {
    title: "Summer Frost",
    genre: "Sci-Fi Thriller",
    rating: 4,
    pages: 85,
    emotionalIntensity: 4,
    year: 2021,
  },
  {
    title: "Ark",
    genre: "Sci-Fi",
    rating: 5,
    pages: 45,
    emotionalIntensity: 3,
    xOverride: 0.3,
    year: 2021,
  },
  {
    title: "Siege and Storm",
    genre: "Fantasy",
    rating: 4,
    pages: 435,
    emotionalIntensity: 3,
    year: 2021,
  },
  {
    title: "The Bridge Kingdom",
    genre: "Fantasy Romance",
    rating: 4,
    pages: 356,
    emotionalIntensity: 5,
    year: 2021,
  },
  {
    title: "A Court of Silver Flames",
    genre: "Fantasy Romance",
    rating: 4,
    pages: 757,
    emotionalIntensity: 5,
    year: 2021,
  },
  {
    title: "Scythe",
    genre: "Sci-Fi Dystopian",
    rating: 3,
    pages: 435,
    emotionalIntensity: 3,
    year: 2021,
  },
  {
    title: "A Darker Shade of Magic",
    genre: "Fantasy",
    rating: 4,
    pages: 400,
    emotionalIntensity: 2,
    year: 2021,
  },
  {
    title: "The Invisible Life of Addie LaRue",
    genre: "Fantasy",
    rating: 5,
    pages: 448,
    emotionalIntensity: 5,
    year: 2021,
    yOverride: 0.5,
  },
  {
    title: "From Blood and Ash",
    genre: "Fantasy Romance",
    rating: 4,
    pages: 630,
    emotionalIntensity: 4,
    year: 2021,
  },
  {
    title: "Serpent & Dove",
    genre: "Fantasy Romance",
    rating: 3,
    pages: 513,
    emotionalIntensity: 3,
    year: 2021,
  },
  {
    title: "The Cruel Prince",
    genre: "Fantasy",
    rating: 3,
    pages: 370,
    emotionalIntensity: 1,
    year: 2021,
  },
  {
    title: "Caraval",
    genre: "Fantasy",
    rating: 3,
    pages: 407,
    emotionalIntensity: 2,
    year: 2021,
  },
  {
    title: "A Court of Thorns and Roses",
    genre: "Fantasy Romance",
    rating: 5,
    pages: 419,
    emotionalIntensity: 5,
    yOverride: 0.15,
    xOverride: 0.3,
    year: 2021,
  },
  {
    title: "House of Earth and Blood",
    genre: "Urban Fantasy",
    rating: 5,
    pages: 803,
    emotionalIntensity: 5,
    yOverride: 0.55,
    year: 2020,
  },
  {
    title: "House of Flame and Shadow",
    genre: "Urban Fantasy",
    rating: 4,
    pages: 835,
    emotionalIntensity: 3,
    year: 2024,
  },
  {
    title: "Dark Matter",
    genre: "Sci-Fi Thriller",
    rating: 5,
    pages: 342,
    emotionalIntensity: 5,
    year: 2020,
    yOverride: 0.20,
  },
  {
    title: "Seveneves",
    genre: "Hard Sci-Fi",
    rating: 5,
    pages: 872,
    emotionalIntensity: 4,
    year: 2020,
    yOverride: 0.72,
  },
  {
    title: "Recursion",
    genre: "Sci-Fi Thriller",
    rating: 5,
    pages: 329,
    emotionalIntensity: 5,
    year: 2019,
  },
  {
    title: "Their War",
    genre: "Sci-Fi Romance",
    rating: 0,
    pages: 419,
    emotionalIntensity: 1,
    year: 2025,
    finished: false,
    yOverride: 0.3,
  },
  {
    title: "Credence",
    genre: "Dark Romance",
    rating: 0,
    pages: 470,
    emotionalIntensity: 1,
    year: 2021,
    finished: false,
  },
  {
    title: "A Deal with the Elf King",
    genre: "Fantasy Romance",
    rating: 0,
    pages: 325,
    emotionalIntensity: 1,
    year: 2021,
    finished: false,
  },
  {
    title: "It Ends with Us",
    genre: "Contemporary Romance",
    rating: 0,
    pages: 373,
    emotionalIntensity: 1,
    year: 2021,
    finished: false,
  },
  {
    title: "The Crown of Gilded Bones",
    genre: "Fantasy Romance",
    rating: 2,
    pages: 645,
    emotionalIntensity: 1,
    yOverride: 0.3,
    year: 2021,
    finished: false,
  },
  {
    title: "A Court of Mist and Fury",
    genre: "Fantasy Romance",
    rating: 4.5,
    pages: 626,
    emotionalIntensity: 4,
    year: 2022,
  },
  {
    title: "A Court of Wings and Ruin",
    genre: "Fantasy Romance",
    rating: 4.5,
    pages: 699,
    emotionalIntensity: 4,
    year: 2022,
  },
  {
    title: "A Court of Frost and Starlight",
    genre: "Fantasy Romance",
    rating: 4,
    pages: 272,
    emotionalIntensity: 1,
    year: 2022,
  },
  {
    title: "Blood Over Bright Haven",
    genre: "Dark Academia",
    rating: 5,
    pages: 428,
    emotionalIntensity: 4,
    yOverride: 0.75,
    year: 2026,
  },
  {
    title: "Veil of Truth and Trickery",
    genre: "Fantasy",
    rating: 3,
    pages: 316,
    emotionalIntensity: 1,
    year: 2022,
  },
];

// ============================================================
//  Supported genre values (copy exactly, case-sensitive):
//
//  "Sci-Fi"  "Fantasy"  "Literary Fiction"  "Fiction"
//  "Mystery"  "Thriller"  "Crime"
//  "Non-Fiction"  "Biography"  "History"
//  "Romance"  "Horror"  "Philosophy"  "Poetry"  "Graphic Novel"
// ============================================================
